# Generated by Django 5.1.1 on 2024-09-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_communication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('predicted_label', models.CharField(max_length=20)),
                ('correct_label', models.CharField(blank=True, max_length=20, null=True)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
    ]
