# Generated by Django 5.1.1 on 2024-09-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_communication', '0002_imagefeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagefeedback',
            name='image',
        ),
        migrations.RemoveField(
            model_name='imagefeedback',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='imagefeedback',
            name='predicted_label',
        ),
        migrations.AddField(
            model_name='imagefeedback',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='imagefeedback',
            name='user_feedback',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='imagefeedback',
            name='correct_label',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
